# Generated by Django 3.1.1 on 2020-10-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ropa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_1', models.ImageField(default='null', upload_to='inventario')),
                ('imagen_2', models.ImageField(default='null', upload_to='inventario')),
                ('imagen_3', models.ImageField(default='null', upload_to='inventario')),
                ('imagen_4', models.ImageField(default='null', upload_to='inventario')),
                ('Titulo', models.TextField()),
                ('Precio', models.IntegerField()),
                ('Descripcion', models.TextField()),
                ('Tallas', models.TextField()),
                ('Colores', models.TextField()),
            ],
        ),
    ]
