# Generated by Django 3.1.1 on 2020-10-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ropa_Hombre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_camiseta', models.BooleanField()),
                ('is_camisa', models.BooleanField()),
                ('is_chaqueta', models.BooleanField()),
                ('is_pantalon', models.BooleanField()),
                ('is_sudadera', models.BooleanField()),
                ('is_accesorio', models.BooleanField()),
                ('imagen_1', models.ImageField(default='null', upload_to='inventario')),
                ('imagen_2', models.ImageField(default='null', upload_to='inventario')),
                ('imagen_3', models.ImageField(default='null', upload_to='inventario')),
                ('imagen_4', models.ImageField(default='null', upload_to='inventario')),
                ('Titulo', models.TextField()),
                ('Precio', models.IntegerField()),
                ('Descripcion', models.TextField()),
                ('Tallas', models.TextField()),
                ('Colores', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Ropa',
        ),
    ]
