# Generated by Django 3.1.1 on 2020-10-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0002_auto_20201007_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='ropa_hombre',
            name='Idn',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ropa_hombre',
            name='Colores',
            field=models.TextField(default='null'),
        ),
    ]
