# Generated by Django 3.1.1 on 2020-10-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0003_auto_20201008_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ropa_hombre',
            name='imagen_1',
            field=models.ImageField(blank=True, null=True, upload_to='inventario'),
        ),
        migrations.AlterField(
            model_name='ropa_hombre',
            name='imagen_2',
            field=models.ImageField(blank=True, null=True, upload_to='inventario'),
        ),
        migrations.AlterField(
            model_name='ropa_hombre',
            name='imagen_3',
            field=models.ImageField(blank=True, null=True, upload_to='inventario'),
        ),
        migrations.AlterField(
            model_name='ropa_hombre',
            name='imagen_4',
            field=models.ImageField(blank=True, null=True, upload_to='inventario'),
        ),
    ]
