# Generated by Django 3.1.1 on 2020-09-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hombre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_camisa', models.BooleanField(default='False')),
                ('es_chaqueta', models.BooleanField(default='False')),
                ('es_pantalon', models.BooleanField(default='False')),
                ('es_accesorio', models.BooleanField(default='False')),
                ('imagen_1', models.ImageField(default='null', upload_to='inventario')),
                ('imagen_2', models.ImageField(default='null', upload_to='inventario')),
                ('imagen_3', models.ImageField(default='null', upload_to='inventario')),
                ('titulo', models.TextField(default='null')),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField(default='null')),
                ('tallas', models.TextField(default='null')),
            ],
        ),
    ]
