# Generated by Django 3.1.1 on 2020-09-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=100)),
                ('nombre', models.TextField()),
                ('apellidos', models.TextField()),
                ('documento', models.TextField(default='(CC) Cédula de ciudadania')),
                ('numero_documento', models.IntegerField()),
                ('departamento', models.TextField()),
                ('ciudad', models.TextField()),
                ('direccion', models.TextField(default='null')),
                ('info', models.TextField(default='null')),
            ],
        ),
    ]
