# Generated by Django 3.1.1 on 2020-09-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_usuario_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='info',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_documento',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='documento',
            field=models.TextField(default='(CC) Cédula de ciudadania'),
        ),
    ]
